import type { Metadata } from 'next'
import { Lora, Open_Sans } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Navigation from '@components/Navigation';

import './vendor/font-awesome/css/font-awesome.min.css'
import './vendor/bootstrap/css/bootstrap.min.css'
import './globals.css'
import './css/clean-blog.min.css'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const open_sans = Open_Sans({ subsets: ['latin'] })
const lora = Lora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Clean Blog</title>
      </Head>
      <UserProvider>

        <body className={`${open_sans.className} ${lora.className}`}>
          <Navigation />

          {children}

          <footer>
            <div className="container">
              <div className="row">
                <div className="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  <ul className="list-inline text-center">
                    <li>
                      <Link href="#">
                        <span className="fa-stack fa-lg">
                          <i className="fa fa-circle fa-stack-2x" />
                          <i className="fa fa-twitter fa-stack-1x fa-inverse" />
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link href="#">
                        <span className="fa-stack fa-lg">
                          <i className="fa fa-circle fa-stack-2x" />
                          <i className="fa fa-facebook fa-stack-1x fa-inverse" />
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link href="#">
                        <span className="fa-stack fa-lg">
                          <i className="fa fa-circle fa-stack-2x" />
                          <i className="fa fa-github fa-stack-1x fa-inverse" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                  <p className="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
              </div>
            </div>
          </footer>
          <ToastContainer />
          <script async src="vendor/jquery/jquery.min.js" />
          <script async src="./vendor/jquery/jquery.min.js" />
          <script async src="./vendor/bootstrap/js/bootstrap.min.js" />

        </body>
      </UserProvider>
    </html>
  )
}
