import type { Metadata } from 'next'
import { Lora, Open_Sans } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import './vendor/font-awesome/css/font-awesome.min.css'
import './vendor/bootstrap/css/bootstrap.min.css'
import './globals.css'
import './css/clean-blog.min.css'
import Hero from '@components/Hero'

const open_sans = Open_Sans({ subsets: ['latin'] })
const lora = Lora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Clean Blog</title>
      </Head>
      <body className={`${open_sans.className} ${lora.className}`}>
        <nav className="navbar navbar-default navbar-custom navbar-fixed-top">
          <div className="container-fluid">
            <div className="navbar-header page-scroll">
              <button type="button" className="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span className="sr-only">Toggle navigation</span>
                Menu <i className="fa fa-bars" />
              </button>
              <Link className="navbar-brand" href="#">Start Bootstrap</Link>
            </div>

            <div className="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul className="nav navbar-nav navbar-right">
                <li>
                  <Link href="index.html">Home</Link>
                </li>
                <li>
                  <Link href="about.html">About</Link>
                </li>
                <li>
                  <Link href="post.html">Sample Post</Link>
                </li>
                <li>
                  <Link href="contact.html">Contact</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {children}

        <footer>
          <div className="container">
            <div className="row">
              <div className="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul className="list-inline text-center">
                  <li>
                    <Link href="#">
                      <span className="fa-stack fa-lg">
                        <i className="fa fa-circle fa-stack-2x" />
                        <i className="fa fa-twitter fa-stack-1x fa-inverse" />
                      </span>
                    </Link>
                  </li>
                  <li>
                    <Link href="#">
                      <span className="fa-stack fa-lg">
                        <i className="fa fa-circle fa-stack-2x" />
                        <i className="fa fa-facebook fa-stack-1x fa-inverse" />
                      </span>
                    </Link>
                  </li>
                  <li>
                    <Link href="#">
                      <span className="fa-stack fa-lg">
                        <i className="fa fa-circle fa-stack-2x" />
                        <i className="fa fa-github fa-stack-1x fa-inverse" />
                      </span>
                    </Link>
                  </li>
                </ul>
                <p className="copyright text-muted">Copyright &copy; Your Website 2016</p>
              </div>
            </div>
          </div>
        </footer>
        <script async src="vendor/jquery/jquery.min.js"></script>
        <script async src="./vendor/jquery/jquery.min.js"></script>
        <script async src="./vendor/bootstrap/js/bootstrap.min.js"></script>

      </body>
    </html>
  )
}
